# Generated by Django 5.2.3 on 2026-02-07 05:08

import django.core.validators
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('short_bio', models.TextField(blank=True)),
                ('full_bio', models.TextField(help_text='Rich text from django CMS text plugin is supported in templates.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True, verbose_name='X / Twitter')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Profile Photo')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('percentage', models.PositiveSmallIntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.teammember')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberDetailPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('section_title', models.CharField(default='Biography', max_length=120)),
                ('description_override', models.TextField(blank=True, help_text='Optional override for the biography text.')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_plugins', to='core.teammember')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TeamMemberListPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('eyebrow', models.CharField(blank=True, help_text='Optional small label shown above the name.', max_length=80)),
                ('summary', models.CharField(blank=True, help_text='Optional text override for the card summary.', max_length=220)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_plugins', to='core.teammember')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
