# Generated by Django 5.2.3 on 2026-02-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("core", "0003_update_skill_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="full_bio",
            field=models.TextField(
                help_text="Rich text from django CMS text plugin is supported in templates."
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="TeamMemberDetailPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "section_title",
                    models.CharField(default="Biography", max_length=120),
                ),
                (
                    "description_override",
                    models.TextField(
                        blank=True,
                        help_text="Optional override for the biography text.",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_plugins",
                        to="core.teammember",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="TeamMemberListPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True,
                        help_text="Optional small label shown above the name.",
                        max_length=80,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Optional text override for the card summary.",
                        max_length=220,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_plugins",
                        to="core.teammember",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
