# Generated by Django 5.2.3 on 2026-02-07 05:08

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsOverviewGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='BrandsPartnersGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CaseStudiesGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CategoryHeader',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('breadcrumb_label', models.CharField(blank=True, max_length=200)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CategoryTeaserGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactFormFull',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('submit_label', models.CharField(default='Send message', max_length=60)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactInfoBlock',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('address_label', models.CharField(blank=True, default='Address', max_length=80)),
                ('address', models.TextField(blank=True)),
                ('phone_label', models.CharField(blank=True, default='Phone', max_length=80)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email_label', models.CharField(blank=True, default='Email', max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hours_label', models.CharField(blank=True, default='Hours', max_length=80)),
                ('hours', models.TextField(blank=True, help_text='Enter hours with one line per row, e.g. Mon-Fri: 08:00-18:00.')),
                ('social_label', models.CharField(blank=True, default='Connect', max_length=80)),
                ('social_links', models.TextField(blank=True, help_text='Enter social links, one per line as Label|URL.')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FeaturedProductsGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GoogleMapEmbed',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('embed_url', models.URLField(blank=True)),
                ('iframe_code', models.TextField(blank=True)),
                ('height', models.PositiveIntegerField(default=360)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('autoplay', models.BooleanField(default=True)),
                ('interval_ms', models.PositiveIntegerField(default=6000)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='IndustriesTeaser',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('badge_text', models.CharField(blank=True, help_text='Optional badge label shown above the cards.', max_length=120)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='KeyProductsGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='LayoutSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('background_style', models.CharField(blank=True, help_text='Bootstrap background utility, e.g. bg-light, bg-primary-subtle.', max_length=100)),
                ('text_alignment', models.CharField(blank=True, help_text='Optional text alignment class, e.g. text-center.', max_length=50)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ManufacturersGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ProductListingGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='QuickContactForm',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True, help_text='Enter benefit bullet points, one per line.')),
                ('helper_text', models.CharField(blank=True, help_text='Optional helper text shown near the submit button.', max_length=160)),
                ('submit_label', models.CharField(default='Request a quote', max_length=60)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SolutionItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SolutionsAccordion',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SubCategoriesGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='BrandHero',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('brand_name', models.CharField(max_length=200)),
                ('eyebrow_text', models.CharField(blank=True, help_text='Optional label above the brand name.', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('banner_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='BrandLogoCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=120)),
                ('short_description', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('button_text', models.CharField(blank=True, default='View brand', max_length=80)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('logo', filer.fields.image.FilerImageField(blank=True, help_text='Suggested: Siemens, SICK, ABB logo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='BrandOverviewCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('button_text', models.CharField(default='Explore', max_length=60)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CaseStudyCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('client_label', models.CharField(blank=True, default='Client', max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('results', models.TextField(blank=True, help_text='Enter bullet items separated by new lines.')),
                ('link_url', models.URLField(blank=True)),
                ('button_text', models.CharField(blank=True, default='Read case study', max_length=80)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CategoryCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome class, e.g. fa-solid fa-microchip.', max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('button_text', models.CharField(blank=True, default='Explore', max_length=80)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='Suggested: industrial automation, sensors, control panels.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactHero',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('eyebrow_text', models.CharField(blank=True, help_text='Optional short label above the title, e.g. Trusted automation partner.', max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_url', models.URLField(blank=True)),
                ('overlay_color', models.CharField(default='#0b1a2a', max_length=20)),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.55, max_digits=3)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='Suggested: industrial automation, Siemens PLC, pharma production.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='IndustryCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('button_text', models.CharField(blank=True, default='See solutions', max_length=80)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='Suggested: pharma production line, clean room.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='IndustryHero',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200)),
                ('eyebrow_text', models.CharField(blank=True, help_text='Optional label above the title.', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('banner_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='KeyProductCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('button_text', models.CharField(blank=True, default='Learn more', max_length=80)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ManufacturerDetailCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('key_lines', models.TextField(blank=True, help_text='Enter bullet items separated by new lines.')),
                ('certificates_label', models.CharField(blank=True, default='Certificates', max_length=80)),
                ('link_url', models.URLField(blank=True)),
                ('button_text', models.CharField(blank=True, default='View catalog', max_length=80)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('certificates', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200)),
                ('model_no', models.CharField(blank=True, max_length=100)),
                ('model_label', models.CharField(blank=True, default='Model', max_length=60)),
                ('short_description', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('button_text', models.CharField(blank=True, default='View details', max_length=80)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='Suggested: industrial automation, PLC, sensor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=200)),
                ('model_no', models.CharField(blank=True, max_length=100)),
                ('model_label', models.CharField(blank=True, default='Model', max_length=60)),
                ('key_specs', models.TextField(blank=True, help_text='Enter bullet items separated by new lines.')),
                ('request_quote_url', models.URLField(blank=True)),
                ('request_quote_label', models.CharField(blank=True, default='Request quote', max_length=80)),
                ('detail_url', models.URLField(blank=True)),
                ('detail_label', models.CharField(blank=True, default='View detail', max_length=80)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SubCategoryCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('product_count', models.PositiveIntegerField(blank=True, null=True)),
                ('link_url', models.URLField(blank=True)),
                ('button_text', models.CharField(blank=True, default='Browse', max_length=80)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
