# Generated by Django 5.2.3 on 2026-02-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_cms_plugins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandhero",
            name="eyebrow_text",
            field=models.CharField(
                blank=True,
                help_text="Optional label above the brand name.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="brandlogocard",
            name="button_text",
            field=models.CharField(blank=True, default="View brand", max_length=80),
        ),
        migrations.AddField(
            model_name="casestudycard",
            name="button_text",
            field=models.CharField(
                blank=True, default="Read case study", max_length=80
            ),
        ),
        migrations.AddField(
            model_name="casestudycard",
            name="client_label",
            field=models.CharField(blank=True, default="Client", max_length=80),
        ),
        migrations.AddField(
            model_name="categorycard",
            name="button_text",
            field=models.CharField(blank=True, default="Explore", max_length=80),
        ),
        migrations.AddField(
            model_name="contactinfoblock",
            name="address_label",
            field=models.CharField(blank=True, default="Address", max_length=80),
        ),
        migrations.AddField(
            model_name="contactinfoblock",
            name="email_label",
            field=models.CharField(blank=True, default="Email", max_length=80),
        ),
        migrations.AddField(
            model_name="contactinfoblock",
            name="hours_label",
            field=models.CharField(blank=True, default="Hours", max_length=80),
        ),
        migrations.AddField(
            model_name="contactinfoblock",
            name="phone_label",
            field=models.CharField(blank=True, default="Phone", max_length=80),
        ),
        migrations.AddField(
            model_name="contactinfoblock",
            name="social_label",
            field=models.CharField(blank=True, default="Connect", max_length=80),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="eyebrow_text",
            field=models.CharField(
                blank=True,
                help_text="Optional short label above the title, e.g. Trusted automation partner.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="industriesteaser",
            name="badge_text",
            field=models.CharField(
                blank=True,
                help_text="Optional badge label shown above the cards.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="industrycard",
            name="button_text",
            field=models.CharField(blank=True, default="See solutions", max_length=80),
        ),
        migrations.AddField(
            model_name="industryhero",
            name="eyebrow_text",
            field=models.CharField(
                blank=True, help_text="Optional label above the title.", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="keyproductcard",
            name="button_text",
            field=models.CharField(blank=True, default="Learn more", max_length=80),
        ),
        migrations.AddField(
            model_name="manufacturerdetailcard",
            name="button_text",
            field=models.CharField(blank=True, default="View catalog", max_length=80),
        ),
        migrations.AddField(
            model_name="manufacturerdetailcard",
            name="certificates_label",
            field=models.CharField(blank=True, default="Certificates", max_length=80),
        ),
        migrations.AddField(
            model_name="productcard",
            name="button_text",
            field=models.CharField(blank=True, default="View details", max_length=80),
        ),
        migrations.AddField(
            model_name="productcard",
            name="model_label",
            field=models.CharField(blank=True, default="Model", max_length=60),
        ),
        migrations.AddField(
            model_name="productitem",
            name="detail_label",
            field=models.CharField(blank=True, default="View detail", max_length=80),
        ),
        migrations.AddField(
            model_name="productitem",
            name="model_label",
            field=models.CharField(blank=True, default="Model", max_length=60),
        ),
        migrations.AddField(
            model_name="productitem",
            name="request_quote_label",
            field=models.CharField(blank=True, default="Request quote", max_length=80),
        ),
        migrations.AddField(
            model_name="quickcontactform",
            name="benefits",
            field=models.TextField(
                blank=True, help_text="Enter benefit bullet points, one per line."
            ),
        ),
        migrations.AddField(
            model_name="quickcontactform",
            name="helper_text",
            field=models.CharField(
                blank=True,
                help_text="Optional helper text shown near the submit button.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="subcategorycard",
            name="button_text",
            field=models.CharField(blank=True, default="Browse", max_length=80),
        ),
    ]
